package org.rf.entities;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

import org.hibernate.annotations.GenericGenerator;

/**
 * Group generated by hbm2java
 */
@Entity
@Table(name = "group_")
public class Group implements java.io.Serializable {

	/**
	 * serialVersionUID
	 */
	private static final long serialVersionUID = -4599040006910652608L;
	private String id;
	private String nama;

	public static final String GROUP_BBM = "1";
	public static final String GROUP_GAS = "2";

	public Group() {
	}

	public Group(String nama) {
		this.nama = nama;
	}

	/**
	 * Gets the id.
	 * 
	 * @return the id
	 * @author Roberto
	 */
	@Id
	@GeneratedValue(generator = "system-uuid")
	@GenericGenerator(name = "system-uuid", strategy = "uuid")
	@Column(name = "ID", unique = true, nullable = false, length = 32)
	public String getId() {
		return id;
	}

	/**
	 * Sets the id.
	 * 
	 * @param id
	 *            the id to set
	 * @author Roberto
	 */
	public void setId(String id) {
		this.id = id;
	}

	@Column(name = "NAMA", length = 250)
	public String getNama() {
		return this.nama;
	}

	public void setNama(String nama) {
		this.nama = nama;
	}

}
